name: Job Scraper Automation

on:
  schedule:
    # Runs every Tuesday and Friday at 10 AM UTC
    - cron: '0 10 * * 2,5'
  workflow_dispatch:  # allows manual run from GitHub

jobs:
  run-job-scraper:
      runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
    run: |
          pip install requests beautifulsoup4

    - name: Debug: List directory contents
    run: ls -la

    - name: Debug: Show current working directory
    run: pwd

    - name: Run the job scraper
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python job_scraper.py

